TechWo/women-in-opensource-hf

github-workshop/CONTRIBUTORS.md

Signed-off-by: rosaq <rosa.quintero@gmail.com>

My first contribution

---

github-workshop/CONTRIBUTORS.md

Signed-off-by: Liz Moreno <malizette@hotmail.com>

mi primer pull

---

github-workshop/CONTRIBUTORS.md

Signed-off-by: Kimbuca <kimbuca.rola@gmail.com>

My first contribution to open source

---

github-workshop/CONTRIBUTORS.md

Signed-off-by: Erendira Garcia <garciaerendira@gmail.com>

Add Erendira Garcia to Contributors

---

github-workshop/CONTRIBUTORS.md

Signed-off-by: MarceStarlet <marcestarlet@techwomen.org.mx>

My first pull request for TechWo

---

best-practices/README_ERENDIRA.md
github-workshop/CONTRIBUTORS.md

Add steps to add remote repository url to local repo

Add best practice

---

best-practices/starting-GitHub.md

I love what you do for all women in technology and I want to contribute with this best practice  guide.

Best practices of starting in GitHub & OpenSource Pull requests

---

best-practices/README-RQ.md

Signed-off-by: rosaq <rosa.quintero@gmail.com>

Best Practices by rosaq

---

github-workshop/CONTRIBUTORS.md

New contributor

---

best-practices/yizia/bestp-yizia.md

Signed-off-by: Yizia Jiménez <yiziaj@gmail.com>

Get the Most Out of the GitHub Platform

---

github-workshop/CONTRIBUTORS.md

Agregar mi bio a Contributors :)

---

github-workshop/CONTRIBUTORS.md

Descripción.
- Me agregué a mí mismo.

Added myself to the Contributors file

---

github-workshop/CONTRIBUTORS.md

Se agregó el contribuidor **Ivan Robles** al MarkDown

Contributor Added

---

github-workshop/CONTRIBUTORS.md

Se agrega nombre de contribuidor en CONTRIBUITORS.md

Datos contribuidor

---

github-workshop/CONTRIBUTORS.md

Aqui están mis datos, muchas gracias por el taller.

Norawashere

---

best-practices/Maye -Receta Pull Request.md
best-practices/README - Pull Request CookBook.md

Se corrigió el formato del Archivo README - Pull Request Cookbook.md

Correcting the issue #32 Pull Request Cookbook Format.

---

best-practices/creating-issues.md

Se agregó un archivo de buenas prácticas para la creación de issues

Agregando archivo de buenas practicas

---

README.md

Signed-off-by: PaulinaFranco <dadiante@gmail.com>

hf image changed

---

README.md

Signed-off-by: Salvador Hernández <saherla03@gmail.com>

Cambio de traducción en bienvenida

---

README.md

Signed-off-by: Salvador Hernández <saherla03@gmail.com>

Agregamos más información

---

README.md

Signed-off-by: Nayeli Angel <nayeli.angel@cimat.mx>

Number of pull request has been updated.

---

github-workshop/CONTRIBUTORS.md

Signed-off-by: Sprunker <54376812+Sprunker@users.noreply.github.com>

Soy Carlos !Vamos a contribuir¡
